name: Deploy to Fly.io
on:
  push:
    branches: [ main ] 
  # TODO: remove when finished so we don't override Master image on pull requests
  # pull_request:
  #   branches: [ master ]

  workflow_dispatch:

env:
  APP_NAME: edin-api
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    name: 🐳 Build
    # needs: [changes]
    # if:
    #   ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    # only build/deploy main branch on pushes
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true # docker build maps to buildx
      # Setup cache
      - name: ⚡️ Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: 🔑 Fly Registry Auth
        uses: docker/login-action@v1
        with:
          registry: registry.fly.io
          username: x
          password: ${{ env.FLY_API_TOKEN }}
      # - name: Create env file for UI-CLIENT app build part
      #   run: |
      #     cd ./client
      #     touch .env
      #     echo REACT_APP_REGION=${{ env.AWS_REGION }} >> .env
      #     echo REACT_APP_USER_POOL_ID=${{ env.COGNITO_POOL_ID }} >> .env
      #     echo REACT_APP_USER_WEB_CLIENT_ID=${{ env.REACT_APP_USER_WEB_CLIENT_ID }} >> .env
      #     echo REACT_APP_WEBSITE_NAME=${{ env.REACT_APP_WEBSITE_NAME }} >> .env
      #     echo REACT_APP_DOMAIN=${{ env.REACT_APP_DOMAIN }} >> .env
      #     echo REACT_APP_API_URL=${{ env.REACT_APP_API_URL }} >> .env
      #     echo REACT_APP_MEDIA_UPLOAD_BUCKET=${{ env.MEDIA_UPLOAD_BUCKET }} >> .env
      #     cat .env
      - name: 🐳 Docker build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: registry.fly.io/${{ env.APP_NAME }}:${{ github.sha }}
          # BUILD TIME ARGUMENTS
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    # needs: [changes, lint, typecheck, jest, build]
    needs: [build]
    # only build/deploy main branch on pushes
    # if:
    #   ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 🚀 Deploy
        uses: superfly/flyctl-actions@1.1
        with:
          args:
            'deploy -i registry.fly.io/${{ env.APP_NAME }}:${{ github.sha }}
            --strategy rolling'
        env:
          FLY_API_TOKEN: ${{ env.FLY_API_TOKEN }}